language: python
python:
  - 2.6
  - 2.7
sudo: false
addons:
  apt:
    packages:
      - libxml2-dev
      - libxslt-dev
env:
  - PLONE=4.0
  - PLONE=4.1
  - PLONE=4.2
  - PLONE=4.3
matrix:
  exclude:
    - python: 2.7
      env: PLONE=4.0
    - python: 2.7
      env: PLONE=4.1
    - python: 2.6
      env: PLONE=4.2
    - python: 2.6
      env: PLONE=4.3
before_install:
  - mkdir -p buildout-cache/{eggs,downloads}
install:
  - python bootstrap.py -c test-$PLONE.x.cfg
  - bin/buildout -t 5 -Nqc test-$PLONE.x.cfg
script:
  - bin/test
